import type { Metadata } from "next";

import { Box } from "@mui/material";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
  return (
    <Box component="html" lang="en">
        <Box component="body" m={0} className={inter.className}>{children}</Box>
    </Box>
  );
}
